/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/brad/catkin_ws/src/rviz_sensor_control_panel/msg/HokuyoCommand.msg
 *
 */


#ifndef RVIZ_SENSOR_CONTROL_PANEL_MESSAGE_HOKUYOCOMMAND_H
#define RVIZ_SENSOR_CONTROL_PANEL_MESSAGE_HOKUYOCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rviz_sensor_control_panel
{
template <class ContainerAllocator>
struct HokuyoCommand_
{
  typedef HokuyoCommand_<ContainerAllocator> Type;

  HokuyoCommand_()
    : header()
    , minTheta(0.0)
    , maxTheta(0.0)
    , degreesPerSecond(0.0)  {
    }
  HokuyoCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , minTheta(0.0)
    , maxTheta(0.0)
    , degreesPerSecond(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _minTheta_type;
  _minTheta_type minTheta;

   typedef float _maxTheta_type;
  _maxTheta_type maxTheta;

   typedef float _degreesPerSecond_type;
  _degreesPerSecond_type degreesPerSecond;




  typedef boost::shared_ptr< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct HokuyoCommand_

typedef ::rviz_sensor_control_panel::HokuyoCommand_<std::allocator<void> > HokuyoCommand;

typedef boost::shared_ptr< ::rviz_sensor_control_panel::HokuyoCommand > HokuyoCommandPtr;
typedef boost::shared_ptr< ::rviz_sensor_control_panel::HokuyoCommand const> HokuyoCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rviz_sensor_control_panel

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'sensor_msgs': ['/opt/ros/groovy/share/sensor_msgs/msg'], 'geometry_msgs': ['/opt/ros/groovy/share/geometry_msgs/msg'], 'rviz_sensor_control_panel': ['/home/brad/catkin_ws/src/rviz_sensor_control_panel/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0d96e98ce1098abcf87d5bfd7e133ed";
  }

  static const char* value(const ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0d96e98ce1098abULL;
  static const uint64_t static_value2 = 0xcf87d5bfd7e133edULL;
};

template<class ContainerAllocator>
struct DataType< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rviz_sensor_control_panel/HokuyoCommand";
  }

  static const char* value(const ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 minTheta\n\
float32 maxTheta\n\
float32 degreesPerSecond\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.minTheta);
      stream.next(m.maxTheta);
      stream.next(m.degreesPerSecond);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HokuyoCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rviz_sensor_control_panel::HokuyoCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "minTheta: ";
    Printer<float>::stream(s, indent + "  ", v.minTheta);
    s << indent << "maxTheta: ";
    Printer<float>::stream(s, indent + "  ", v.maxTheta);
    s << indent << "degreesPerSecond: ";
    Printer<float>::stream(s, indent + "  ", v.degreesPerSecond);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVIZ_SENSOR_CONTROL_PANEL_MESSAGE_HOKUYOCOMMAND_H
